server:
  log_level: info

metrics:
  global:
    remote_write:
      - url: https://prometheus-prod-XX-XXXXX.grafana.net/api/prom/push
        basic_auth:
          username: YOUR_INSTANCE_ID
          password: YOUR_API_KEY

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: https://logs-prod-XX-XXXXX.grafana.net/loki/api/v1/push
          basic_auth:
            username: YOUR_INSTANCE_ID
            password: YOUR_API_KEY
      scrape_configs:
        - job_name: address-service
          static_configs:
            - targets:
                - localhost
              labels:
                job: address-service
                __path__: /app/logs/*.log

traces:
  configs:
    - name: default
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      remote_write:
        - endpoint: https://tempo-prod-XX-XXXXX.grafana.net:443
          tls:
            insecure: false
          basic_auth:
            username: YOUR_INSTANCE_ID
            password: YOUR_API_KEY 