apiVersion: v1
kind: Namespace
metadata:
  name: address-service
  labels:
    name: address-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-service-config
  namespace: address-service
data:
  LOG_LEVEL: "info"
  NODE_ENV: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service
  namespace: address-service
  labels:
    app: address-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: address-service
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
      - name: address-service
        image: docker.io/your-username/address-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: address-service-config
              key: LOG_LEVEL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: address-service-config
              key: NODE_ENV
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: address-service
  namespace: address-service
  labels:
    app: address-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: address-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: address-service-hpa
  namespace: address-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: address-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 