# Development environment values
replicaCount: 1

image:
  repository: docker.io/jblayter/address-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  NODE_ENV: "development"
  LOG_LEVEL: "debug"
  PORT: "3000"

# Disable security contexts for easier development
podSecurityContext: {}
securityContext: {} 