# Production environment values
replicaCount: 2

image:
  repository: docker.io/jblayter/address-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"

# Enable HPA for production
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Enable PDB for production
podDisruptionBudget:
  enabled: true
  minAvailable: 1 